# ================================
# Starship minimal config
# ================================

add_newline = false

format = """
[î‚° ](fg:#7aa2f7 bg:#1a1b26)\
$sudo\
$time\
$directory\
$git_branch\
$git_status\
$direnv\
$nodejs\
$java\
$docker_context\
[î‚°](fg:#1a1b26)\
$fill\
[î‚´](fg:#9ece6a)\
\n$character\
"""

right_format = """
$cmd_duration
"""

[time]
disabled = false
time_format = "%T"
style = "lavender"
format = '[ $time | ]($style)'

[directory]
truncation_length = 6
truncation_symbol = 'ï¼ ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = 'î˜— ~' # nf-costum-home
style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' ó°Œ¾ ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = 'ï„“ ï„¦ ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#7aa2f7 bg:#1a1b26'
format = '[ î‚± $symbol$branch(:$remote_branch)]($style) ' # nf-pl-left_soft_divider

[git_status]
style = "bold red"
ahead = "â†‘${count}"
diverged = "â†•â†‘${ahead_count}â†“${behind_count}"
behind = "â†“${count}"
# ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã®è¨­å®šã‚’å‡ºã•ãªã„ã‚ˆã†ã«""ã«ã—ã¦ã„ã‚‹ã€‚
modified = ""
staged = ""
untracked = ""
renamed = ""
deleted = ""
stashed = ""
conflicted = ""

[fill]
symbol = 'â”€'
style = 'blue'

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[direnv]
format = '[î‚¼$symbol$allowedî‚º]($style) '
style = "bold fg:#1a1b26 bg:#cba6f7"
disabled = false

#[cmd_duration]
#min_time = 1
#style = 'fg:#e0af68'
#format = "[ î‚³ î‚ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

# ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°è¨€èªå›ºæœ‰è¨­å®š
[nodejs]
symbol = "â¬¢ "
style = "bold green"

[java]
symbol = "â˜• "
style = "bold red"

# Docker
[docker_context]
symbol = "ğŸ³ "
style = "bold blue"

